In [1]:
import pandas as pd
import numpy as np


In [3]:
df= pd.concat ([

    pd.read_csv('Youtube01-Psy.csv'),
    pd.read_csv('Youtube02-KatyPerry.csv'),
    pd.read_csv('Youtube03-LMFAO.csv'),
    pd.read_csv('Youtube04-Eminem.csv'),
    pd.read_csv('Youtube05-Shakira.csv')
])



df

COMMENT_ID                AUTHOR  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
..                                           ...                   ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                           DATE  \
0           2013-11-07T06:20:48   
1           2013-11-07T12:37:15   
2           2013-11-08T17:34:21   
3           2013-11-09T08:28:43   
4           2013-11-10T16:05:38   
..                          ...   
365  2013-07-13T13:27:39.441000   
366  2013-07-13T13:14:30.021000   
367  2013-07-13T12:09:31.188000   
368  2013-07-13T11:17:52.308000   
369  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1956 entries, 0 to 369
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  1956 non-null   object
 1   AUTHOR      1956 non-null   object
 2   DATE        1711 non-null   object
 3   CONTENT     1956 non-null   object
 4   CLASS       1956 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 91.7+ KB


In [5]:
from sklearn.model_selection import train_test_split
seed=123

x_train,x_test,y_train,y_test=train_test_split(df['CONTENT'],df['CLASS'], test_size=0.2, random_state=seed)


In [6]:
x_train.shape

(1564,)

In [7]:
y_train.shape

(1564,)

In [8]:
x_test.shape

(392,)

In [9]:
y_test.shape

(392,)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestClassifier

pipe=make_pipeline(
    CountVectorizer(),
    RandomForestClassifier(random_state=seed)


)
print(pipe)

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(random_state=123))])


In [11]:
pipe_fitted=pipe.fit(x_train,y_train)

In [12]:
pipe_fitted

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('randomforestclassifier',
                 RandomForestClassifier(random_state=123))])

In [13]:
pipe_fitted.score(x_test,y_test)

0.9617346938775511

In [14]:
pipe_fitted.predict(['What a good video'])

array([0])

In [15]:
pipe_fitted.predict(['click here to have free phone'])

array([1])

In [16]:
from sklearn.model_selection import cross_val_score

score=cross_val_score(pipe,x_train,y_train,cv=3)

In [17]:
score

array([0.94827586, 0.95585413, 0.94241843])

In [18]:
score.mean()

0.9488494716173582

In [19]:
score.std()

0.005500077782859053

In [20]:
# REGLAGE D'HYPERPARAMETRES

In [39]:

parameters ={
    'countvectorizer__max_features':(None,1000,2000),
    'countvectorizer__ngram_range':((1,1),(1,2)),
    'countvectorizer__stop_words': (None,'english'),
    'randomforestclassifier__n_estimators':(50,100,200)

}

print(parameters)

{'countvectorizer__max_features': (None, 1000, 2000), 'countvectorizer__ngram_range': ((1, 1), (1, 2)), 'countvectorizer__stop_words': (None, 'english'), 'randomforestclassifier__n_estimators': (50, 100, 200)}


In [40]:
from sklearn.model_selection import GridSearchCV
search_model=GridSearchCV(pipe,parameters,cv=3,n_jobs=-1)
search_model

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('countvectorizer', CountVectorizer()),
                                       ('randomforestclassifier',
                                        RandomForestClassifier(random_state=123))]),
             n_jobs=-1,
             param_grid={'countvectorizer__max_features': (None, 1000, 2000),
                         'countvectorizer__ngram_range': ((1, 1), (1, 2)),
                         'countvectorizer__stop_words': (None, 'english'),
                         'randomforestclassifier__n_estimators': (50, 100,
                                                                  200)})

In [41]:
search_model.fit(x_train,y_train)
search_model.best_params_
search_model.best_score_

0.9571655844076256

In [42]:
search_model.best_params_

{'countvectorizer__max_features': 1000,
 'countvectorizer__ngram_range': (1, 2),
 'countvectorizer__stop_words': 'english',
 'randomforestclassifier__n_estimators': 50}

In [44]:
# ENREGISTRER LE MODEL
import joblib
joblib.dump(value=search_model.best_estimator_,filename='detector_model.pkl')

['detector_model.pkl']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [45]:
# Chargement du model
loaded_model=joblib.load(filename='detector_model.pkl')

In [47]:
loaded_model.predict(['Good bye'])

array([0])